install:
  # Install and start kafka
  # - curl http://mirrors.ibiblio.org/apache/kafka/0.8.1.1/kafka_2.9.2-0.8.1.1.tgz > kafka.tgz
  # - tar -xzf kafka.tgz
  # - cd kafka_2.9.2-0.8.1.1
  # - ./bin/zookeeper-server-start.sh config/zookeeper.properties &
  # - sleep 3
  # - ./bin/kafka-server-start.sh config/server.properties &
  # - sleep 5
  # - ./bin/kafka-topics.sh --zookeeper localhost:2181 --topic foobar --partition 1 --replication-factor 1 --create
  # - cd ../

  # Install librdkafka
  - wget https://github.com/edenhill/librdkafka/archive/master.tar.gz
  - tar xzvf master.tar.gz
  - cd librdkafka-master
  - ./configure
  - make
  - sudo make install
  - cd ../

language: crystal
